#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
	typeit=1
	shift
fi

contact=$(cat ~/.contacts | rofi -dmenu -p "contact: ")
[[ -n $contact ]] || exit

if [[ $typeit -eq 0 ]]; then
	grep -i -A 2 $contact ~/.contacts
else
    echo "No contact found"
fi
