#!/usr/bin/env bash

vcf="$HOME/.contacts.vcf"

if [ ! -f "$vcf" ]
then
	    echo "Please download contacts card and place it in ~/.contacts.vcf"
fi

if ! which choose >> /dev/null
then
	echo 'Please install choose-gui (https://github.com/sdegutis/choose)'
	exit 1
fi

contact="$(grep 'FN' "$vcf" | cut -d":" -f2- | sed '/^\s*$/d' | choose)"

if [[ $typeit -eq 0 ]]; then
    grep -i -A 20 "$contact" $vcf \
        | grep '\(([0-9]\{3\})\|[0-9]\{3\}\)[ -]\?[0-9]\{3\}[ -]\?[0-9]\{4\}' \
        | head -1 \
        | cut -d":" -f2- \
        | tr -d '\r' \
	| tr -d '\n' \
        | pbcopy    
else 
    exit 1
fi
